spring:
  application:
    name: hotel-search-challenge

  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_search
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hotel-search-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    producer:
      properties:
        spring.json.add.type.headers: false

server:
  port: 8080