spring:
  application:
    name: hotel-search-challenge

  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_search
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: hotel-search-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.challenge.infrastructure.adapter.out.kafka.dto.SearchCreatedEvent
        spring.json.trusted.packages: com.challenge

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080